name: Tests

on: pull_request

jobs:
  rspec:
    name: rspec tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - name: Run rspec tests
        run: |
          bundle exec rspec


      - name: Upload coverage results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-results
          path: coverage
          retention-days: 5
          include-hidden-files: true

  coverage:
    needs: rspec
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download coverage results
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: coverage-results
          path: coverage

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@7fd5fa551dd583dd437a11c640b2a1cf23d6cdaa # v1.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: 100
          resultPath: coverage/.last_run.json
